### ISSUE TITLE
Collector doesn't fetch country-specific content?

### ISSUE THREAD

**Issue by pax** [smlabto/polidashboard#3]
I have managed to run collector.py. Problem seems to be that no matter what country I try (id, de, ro), I get unrelated  ads - unrelated in the sense that are different languages or regions (irrelevant to the choosen country)

*I had to tweak it a bit as it would halt for ads that had no lower or upper bound for impressions or ad spent.

<img width="1160" alt="Screenshot 2023-12-30 at 10 51 10" src="https://github.com/smlabto/polidashboard/assets/116795/b7076cd6-a084-48df-9774-d5f77e7e8853">
<img width="1160" alt="Screenshot 2023-12-30 at 10 50 45" src="https://github.com/smlabto/polidashboard/assets/116795/7876d1c5-b52d-4457-a699-ec5539e6d9eb">
<img width="1160" alt="Screenshot 2023-12-30 at 10 50 21" src="https://github.com/smlabto/polidashboard/assets/116795/c6e414a3-8fb1-4d01-909b-e95e5189a33d">

**Comment by tiago-a-ribeiro** [comment]
Even though it may seem these ads are un-related to the country, they may be "targeted" towards a country. I tested this on my ending by running it on `ro` and I was able to capture the same ad in your last screenshot, the one with `'id': '223065290755898'`.

One of the fields in the ad is 'target_locations', here is the target locations for the ad of your last screenshot
`'target_locations': [{'name': 'Spain', 'num_obfuscated': 0, 'type': 'countries', 'excluded': False}, {'name': 'Portugal', 'num_obfuscated': 0, 'type': 'countries', 'excluded': False}, {'name': 'Romania', 'num_obfuscated': 0, 'type': 'countries', 'excluded': False}]` (this field can be seen in the print output of the collect.py script)

As can be seen, Romania is one of the targeted countries for this ad, so while it may not have originated from a country it can be targeted towards it, hope this helps.

> *I had to tweak it a bit as it would halt for ads that had no lower or upper bound for impressions or ad spent.

Also going to ad a fix for this issue, thank you for pointing it out.

**Comment by pax** [comment]
acknowledged, thank you!
I was put off by the bulk of seemingly off-topic records. Are these all _political ads,_ or just all meta ads? For what I have fetched thus far, there's not even one page which has 'partid' (party) in the name. 

See this a 5k records sample: [polidashboard.facebook_ads_ro 5k 240109](https://docs.google.com/spreadsheets/d/1Hx-5-OmgUi3O3IwE9nGVjpzLbp4b2ZS_/) – mostly gibberish (as in almost no political ads – skimming over it I only found 2 that would qualify). The `delivery_by_region` fields seem fine - having exclusively Romanian regions. On this note, @Lejo1's [facebook political ad library dump](https://github.com/Lejo1/facebook_ad_library) seems to only/mostly yield relevant (political) ads.



![pd Kapture 2024-01-09 at 18 38 29](https://github.com/smlabto/polidashboard/assets/116795/c8003da3-ac89-4e47-898f-14859b6de694)
![polidash Kapture 2024-01-09 at 18 15 55](https://github.com/smlabto/polidashboard/assets/116795/cfce9d16-e969-421f-933c-540779dc6f55)

PS: It might potentially help to have the explicit url in the readme, it took me a bit to click on the image.

**Comment by tiago-a-ribeiro** [comment]
These are not political ads, this was an oversight on my part.

If you look at commit 997b86f it is necessary to change the url to collect _ONLY_ political ads, sorry if this caused confusion. Just replace the url with the one in that commit and it should collect relevant political ads.
